name: Sync Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Copy README.md and LICENSE.md to .github directory
        run: |
          mkdir -p .github
          cp documentation/readme.md .github/readme.md
          cp documentation/license.md .github/license.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .github/readme.md .github/license.md
          git diff --cached --quiet || git commit -m "Sync README.md and LICENSE.md to .github directory"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" master